const http = require('http');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const os = require('os');
const port = Number(process.env.PORT) || 4173;
const root = __dirname;
const dataDir = process.env.DATA_DIR ? path.resolve(process.env.DATA_DIR) : path.join(root, 'data');
const dbFile = path.join(dataDir, 'db.json');
const courtsCacheFile = path.join(dataDir, 'courts-cache.json');
const types = { '.html':'text/html; charset=utf-8', '.css':'text/css; charset=utf-8', '.js':'text/javascript; charset=utf-8', '.png':'image/png', '.ico':'image/x-icon' };
const courts = [
  {id:'parque-santana',name:'Parque Santana Ariano Suassuna',area:'Santana',lat:-8.0298,lon:-34.9147,light:true,surface:'Piso esportivo',open:'22h',source:'verified'},
  {id:'parque-jaqueira',name:'Parque da Jaqueira',area:'Jaqueira',lat:-8.0363,lon:-34.9045,light:true,surface:'Concreto',open:'22h',source:'verified'}
];
function demoUsers(){return [['Ruan Deud','ruan@bastreet.demo','quadra123','Homem',184,'Armador',76,'player'],['João Guilherme','joao@bastreet.demo','quadra123','Homem',182,'Ala-armador',78,'player'],['Daniel Moura','daniel@bastreet.demo','quadra123','Homem',191,'Pivô',74,'player'],['Bárbara Menezes','barbara@bastreet.demo','quadra123','Mulher',177,'Ala',80,'player'],['Administrador BASTREET','admin@teste.com','admin123','Prefiro não informar',180,'Administrador',85,'admin']].map(([name,email,password,gender,height,position,skill,role])=>{const pass=secure(password);return {id:crypto.randomUUID(),name,email,passwordHash:pass.hash,salt:pass.salt,age:21,height,location:'Recife, PE',position,gender,level:'Intermediário',availability:['Ter','Qui','Sáb'],skill,xp:0,semesterPoints:0,role,createdAt:new Date().toISOString()}})}
function initialDb(){return {users:process.env.SEED_DEMO==='true'?demoUsers():[],sessions:[],trainings:[],checkins:[],messages:[{id:crypto.randomUUID(),userId:'bot',userName:'Rafael (bot)',text:'Bem-vindos ao grupo! Quem topa um treino hoje às 19h?',createdAt:new Date().toISOString()}],queue:[],matches:[],eventParticipants:[]}}
function readDb(){if(!fs.existsSync(dataDir))fs.mkdirSync(dataDir,{recursive:true});if(!fs.existsSync(dbFile))fs.writeFileSync(dbFile,JSON.stringify(initialDb(),null,2));return JSON.parse(fs.readFileSync(dbFile,'utf8'))}
function writeDb(db){const temp=`${dbFile}.tmp`;fs.writeFileSync(temp,JSON.stringify(db,null,2));fs.renameSync(temp,dbFile)}
function json(res,status,value){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(value))}
function body(req){return new Promise((resolve,reject)=>{let data='';req.on('data',chunk=>{data+=chunk;if(data.length>1e6)reject(new Error('Payload grande'))});req.on('end',()=>{try{resolve(data?JSON.parse(data):{})}catch{reject(new Error('JSON inválido'))}})})}
function secure(password,salt=crypto.randomBytes(16).toString('hex')){return {salt,hash:crypto.scryptSync(password,salt,64).toString('hex')}}
function safe(user){const {passwordHash,salt,...result}=user;return result}
function currentUser(req,db){const token=(req.headers.authorization||'').replace(/^Bearer /,'');const session=db.sessions.find(item=>item.token===token);return session?db.users.find(user=>user.id===session.userId):null}
function requireUser(req,res,db){const user=currentUser(req,db);if(!user)json(res,401,{error:'Faça login para continuar.'});return user}
function km(a,b,c,d){const r=v=>v*Math.PI/180;const x=Math.sin(r(c-a)/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(r(d-b)/2)**2;return 6371*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function balance(players){const sorted=[...players].sort((a,b)=>b.skill-a.skill),teams=[[],[]],totals=[0,0];sorted.forEach(player=>{const target=totals[0]<=totals[1]?0:1;teams[target].push(safe(player));totals[target]+=player.skill});return teams}
function botResponse(text){const lower=text.toLowerCase();let pool;if(/oi|olá|bom dia|boa tarde|boa noite/.test(lower))pool=[['Rafael','Fala! Bora organizar um jogo hoje? 🏀'],['Mariana','Oi! Chegou na hora certa, estamos fechando um grupo.'],['Lucas','Salve! Já conferiu as quadras perto de você?']];else if(/hor|quando|que dia/.test(lower))pool=[['Rafael','Consigo hoje às 19:30 ou sábado às 16h. Qual fica melhor?'],['Mariana','Quinta às 20h funciona para mim.'],['Lucas','No sábado consigo chegar mais cedo, por volta das 15:30.']];else if(/vaga|entrar|jogar|partida/.test(lower))pool=[['Rafael','Tem vaga sim! Entra pelo card da partida e eu confirmo o grupo.'],['Mariana','Bora! Ainda precisamos de mais duas pessoas para equilibrar os times.'],['Lucas','Pode entrar. O sistema monta os times quando o grupo fechar.']];else if(/quadra|onde|local|recife|torre/.test(lower))pool=[['Mariana','Olha a aba Quadras: ela usa seu GPS e ordena tudo por distância.'],['Rafael','Perto da Torre costuma aparecer opção na Jaqueira e no Parque Santana.'],['Lucas','Abre “Como chegar” no card da quadra que ele monta a rota no Google Maps.']];else if(/treino|xp|ponto|ranking/.test(lower))pool=[['Mariana','Treino individual dá XP, mas o coletivo vale o dobro de pontos semestrais.'],['Rafael','Mantém a sequência diária e entra num treino em grupo para acelerar sua evolução.'],['Lucas','O ranking é semestral; para formar times usamos seu nível técnico, não sua posição.']];else if(/bola|levar/.test(lower))pool=[['Rafael','Eu levo a bola hoje! Só tragam água.'],['Mariana','Tenho uma bola reserva, posso levar também.']];else pool=[['Rafael','Fechado! Vou avisar o restante do grupo 🙌'],['Mariana','Boa! Quer marcar treino ou já procurar uma partida?'],['Lucas','Combinado. Se precisar, vejo quem está disponível agora.'],['Rafael','Perfeito! Confere o mapa e me diz qual quadra fica melhor.']];return pool[Math.floor(Math.random()*pool.length)]}
function readCourtCache(){try{return JSON.parse(fs.readFileSync(courtsCacheFile,'utf8'))}catch{return null}}
async function searchOsmCourts(lat,lon,radius=8000,force=false){
  const cache=readCourtCache(),fresh=cache&&Date.now()-new Date(cache.updatedAt).getTime()<86400000,sameArea=cache?.center&&km(lat,lon,cache.center.lat,cache.center.lon)<2,enoughRadius=(cache?.radius||0)>=radius;
  if(cache&&fresh&&sameArea&&enoughRadius&&!force)return {...cache,cache:true};
  const query=`[out:json][timeout:25];nwr(around:${radius},${lat},${lon})["sport"="basketball"];out center tags;`;
  try{
    const endpoints=['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter'];let data,lastError;
    for(const endpoint of endpoints){try{const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','User-Agent':'BASTREET-Academic-MVP/1.0'},body:`data=${encodeURIComponent(query)}`,signal:AbortSignal.timeout(28000)});if(!response.ok)throw new Error(`${response.status}`);data=await response.json();break}catch(error){lastError=error}}
    if(!data)throw new Error(`Todos os provedores falharam: ${lastError?.message||'indisponível'}`);
    const results=data.elements.map(item=>{const tags=item.tags||{},point=item.center||item;return {id:`osm-${item.type}-${item.id}`,name:tags.name||'Quadra de basquete',area:tags['addr:suburb']||tags['addr:neighbourhood']||'Região próxima',lat:point.lat,lon:point.lon,light:tags.lit==='yes',surface:tags.surface||'Não informada',open:tags.opening_hours||'Não informado',access:tags.access||'yes',hoops:tags.hoops||null,source:'osm'}}).filter(item=>Number.isFinite(item.lat)&&Number.isFinite(item.lon));
    const value={updatedAt:new Date().toISOString(),center:{lat,lon},radius,results};fs.writeFileSync(courtsCacheFile,JSON.stringify(value,null,2));return {...value,cache:false};
  }catch(error){console.error('Falha no Overpass:',error.message);if(cache)return {...cache,cache:true,stale:true};return {updatedAt:null,results:[],cache:true,stale:true}}
}

async function api(req,res,url){
  const db=readDb(),method=req.method;
  if(method==='GET'&&url.pathname==='/api/health')return json(res,200,{status:'ok',service:'bastreet',time:new Date().toISOString()});
  if(method==='POST'&&url.pathname==='/api/auth/register'){
    const input=await body(req),email=String(input.email||'').trim().toLowerCase();
    if(!email.includes('@')||String(input.password||'').length<6||!String(input.name||'').trim())return json(res,400,{error:'Preencha nome, e-mail válido e senha com 6 caracteres.'});
    if(db.users.some(user=>user.email===email))return json(res,409,{error:'Este e-mail já está cadastrado.'});
    const pass=secure(input.password);const user={id:crypto.randomUUID(),name:String(input.name).trim(),email,passwordHash:pass.hash,salt:pass.salt,age:Number(input.age)||18,height:Number(input.height)||175,location:input.location||'Recife, PE',position:input.position||'Ala',gender:input.gender||'Prefiro não informar',level:input.level||'Iniciante',availability:input.availability||[],skill:input.level==='Avançado'?82:input.level==='Intermediário'?72:60,xp:0,semesterPoints:0,role:'player',createdAt:new Date().toISOString()};
    const token=crypto.randomBytes(24).toString('hex');db.users.push(user);db.sessions.push({token,userId:user.id});writeDb(db);return json(res,201,{token,user:safe(user)});
  }
  if(method==='POST'&&url.pathname==='/api/auth/login'){
    const input=await body(req),user=db.users.find(item=>item.email===String(input.email||'').trim().toLowerCase());
    if(!user||secure(String(input.password||''),user.salt).hash!==user.passwordHash)return json(res,401,{error:'E-mail ou senha incorretos.'});
    const token=crypto.randomBytes(24).toString('hex');db.sessions=db.sessions.filter(item=>item.userId!==user.id);db.sessions.push({token,userId:user.id});writeDb(db);return json(res,200,{token,user:safe(user)});
  }
  if(method==='GET'&&url.pathname==='/api/me'){const user=requireUser(req,res,db);if(user)return json(res,200,{user:safe(user)});return}
  if(method==='GET'&&url.pathname==='/api/courts'){
    const lat=Number(url.searchParams.get('lat'))||-8.0476,lon=Number(url.searchParams.get('lon'))||-34.9084,now=Date.now(),force=url.searchParams.get('refresh')==='1';db.checkins=db.checkins.filter(item=>now-new Date(item.createdAt).getTime()<14400000);writeDb(db);
    let radius=Math.min(30000,Math.max(8000,Number(url.searchParams.get('radius'))||8000));let osm=await searchOsmCourts(lat,lon,radius,force);if(osm.results.length<3&&radius<25000){radius=25000;osm=await searchOsmCourts(lat,lon,radius,true)}const verified=courts.filter(court=>km(lat,lon,court.lat,court.lon)<=radius/1000);const seen=new Set(verified.map(court=>court.name.toLowerCase()));const merged=[...verified,...osm.results.filter(court=>!seen.has(court.name.toLowerCase()))];
    return json(res,200,{courts:merged.map(court=>({...court,distance:km(lat,lon,court.lat,court.lon),players:db.checkins.filter(item=>item.courtId===court.id).length})).sort((a,b)=>a.distance-b.distance),meta:{cache:osm.cache,stale:Boolean(osm.stale),updatedAt:osm.updatedAt,osmResults:osm.results.length,radius:radius/1000,expanded:radius>8000}});
  }
  const checkin=url.pathname.match(/^\/api\/courts\/([^/]+)\/checkin$/);
  if(method==='POST'&&checkin){const user=requireUser(req,res,db);if(!user)return;db.checkins=db.checkins.filter(item=>item.userId!==user.id);db.checkins.push({userId:user.id,userName:user.name,courtId:checkin[1],createdAt:new Date().toISOString()});writeDb(db);return json(res,200,{ok:true})}
  if(method==='GET'&&url.pathname==='/api/messages')return json(res,200,{messages:db.messages.slice(-60)});
  if(method==='POST'&&url.pathname==='/api/messages'){const user=requireUser(req,res,db);if(!user)return;const input=await body(req),text=String(input.text||'').trim().slice(0,500);if(!text)return json(res,400,{error:'Mensagem vazia.'});const message={id:crypto.randomUUID(),userId:user.id,userName:user.name,text,createdAt:new Date().toISOString()};db.messages.push(message);writeDb(db);const [botName,reply]=botResponse(text);setTimeout(()=>{try{const fresh=readDb();fresh.messages.push({id:crypto.randomUUID(),userId:`bot-${botName.toLowerCase()}`,userName:`${botName} (bot)`,text:reply,createdAt:new Date().toISOString()});writeDb(fresh)}catch(error){console.error('Bot:',error.message)}},700+Math.floor(Math.random()*900));return json(res,201,{message,botPending:true})}
  if(method==='POST'&&url.pathname==='/api/trainings'){const user=requireUser(req,res,db);if(!user)return;const input=await body(req),day=new Date().toISOString().slice(0,10);if(db.trainings.some(item=>item.userId===user.id&&item.workoutId===input.workoutId&&item.day===day))return json(res,409,{error:'Treino já concluído hoje.'});const xp=Math.max(10,Math.min(150,Number(input.xp)||40)),points=input.collective?xp*2:Math.round(xp*.5);user.xp+=xp;user.semesterPoints+=points;user.skill=Math.min(99,user.skill+(input.collective?2:1));db.trainings.push({id:crypto.randomUUID(),userId:user.id,workoutId:input.workoutId,day,xp,points,collective:Boolean(input.collective)});writeDb(db);return json(res,201,{user:safe(user),xp,points})}
  if(method==='POST'&&url.pathname==='/api/matchmaking/join'){const user=requireUser(req,res,db);if(!user)return;const input=await body(req);db.queue=db.queue.filter(item=>item.userId!==user.id);db.queue.push({userId:user.id,slot:input.slot||'Terça • 19h',createdAt:new Date().toISOString()});const queued=db.queue.map(item=>db.users.find(user=>user.id===item.userId)).filter(Boolean);let match=null;if(queued.length>=4){const selected=queued.slice(0,4);match={id:crypto.randomUUID(),teams:balance(selected),court:courts[0],createdAt:new Date().toISOString()};db.matches.push(match);db.queue=db.queue.filter(item=>!selected.some(user=>user.id===item.userId))}writeDb(db);return json(res,200,{waiting:match?0:queued.length,needed:4,match})}
  if(method==='GET'&&url.pathname==='/api/matchmaking/status'){const user=requireUser(req,res,db);if(!user)return;const match=[...db.matches].reverse().find(item=>item.teams.flat().some(player=>player.id===user.id));return json(res,200,{match,waiting:db.queue.length,needed:4})}
  if(method==='GET'&&url.pathname==='/api/ranking')return json(res,200,{users:db.users.map(safe).sort((a,b)=>b.semesterPoints-a.semesterPoints)});
  const eventJoin=url.pathname.match(/^\/api\/events\/([^/]+)\/join$/);
  if(method==='POST'&&eventJoin){const user=requireUser(req,res,db);if(!user)return;db.eventParticipants=db.eventParticipants||[];const exists=db.eventParticipants.some(item=>item.eventId===eventJoin[1]&&item.userId===user.id);if(!exists)db.eventParticipants.push({eventId:eventJoin[1],userId:user.id,userName:user.name,joinedAt:new Date().toISOString()});writeDb(db);const participants=db.eventParticipants.filter(item=>item.eventId===eventJoin[1]);return json(res,200,{joined:true,count:participants.length,participants})}
  const eventStatus=url.pathname.match(/^\/api\/events\/([^/]+)$/);
  if(method==='GET'&&eventStatus){db.eventParticipants=db.eventParticipants||[];return json(res,200,{participants:db.eventParticipants.filter(item=>item.eventId===eventStatus[1])})}
  return json(res,404,{error:'Rota não encontrada.'});
}

http.createServer(async(req,res)=>{
  const url=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);try{if(url.pathname.startsWith('/api/'))return await api(req,res,url)}catch(error){console.error(error);return json(res,500,{error:'Erro interno do servidor.'})}
  const relative=url.pathname==='/'?'index.html':decodeURIComponent(url.pathname).replace(/^\/+/,''),file=path.resolve(root,relative);if(!file.startsWith(root)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404);res.end('Not found');return}if(relative==='index.html'){const protocol=String(req.headers['x-forwarded-proto']||'http').split(',')[0],host=String(req.headers.host||`localhost:${port}`).replace(/[^a-zA-Z0-9.:-]/g,''),base=`${protocol}://${host}`,html=fs.readFileSync(file,'utf8').replaceAll('__BASE_URL__',base);res.writeHead(200,{'Content-Type':types['.html']});res.end(html);return}res.writeHead(200,{'Content-Type':types[path.extname(file)]||'application/octet-stream'});fs.createReadStream(file).pipe(res);
}).listen(port,'0.0.0.0',()=>{const addresses=Object.values(os.networkInterfaces()).flat().filter(item=>item&&item.family==='IPv4'&&!item.internal).map(item=>`http://${item.address}:${port}`);console.log(`BASTREET local: http://localhost:${port}`);addresses.forEach(address=>console.log(`BASTREET na rede: ${address}`))});
